Update jenkinfile

diff --git a/interview-devops-sing-company-jenkinlocation/jenkinfile b/interview-devops-sing-company-jenkinlocation/jenkinfile
--- a/interview-devops-sing-company-jenkinlocation/jenkinfile
+++ b/interview-devops-sing-company-jenkinlocation/jenkinfile
@@ -3,9 +3,10 @@ pipeline {
     stages {
         stage('Build') { 
             steps {
-                sh 'echo buid step with the ${PYTHON_BASE_VERSION} python base version!'
-                sh 'echo buid step with the ${APP_VERSION} python app version!'
                 script {
+                    sh 'echo buid step with the ${PYTHON_BASE_VERSION} python base version!'
+                    sh 'echo buid step with the ${APP_VERSION} python app version!'
+
                     // Check if requirement is set and not empty
                     if (env.requirement?.trim()) {
                         // Run the command only if requirement is not empty
@@ -37,21 +38,23 @@ pipeline {
         }
         stage('Test') { 
             steps {
-                sh 'echo test the app image'
-                // Run the image in detach mode and map container port 5000 to localhost:5000
-                sh '''#!/bin/bash
-                docker run -d -p localhost:5000:5000 wizard-almanac:${APP_VERSION}
-                '''      
-                //Make a test reuest to the app and check result
-                sh 'curl localhost:5000 | grep "Welcome to the Wizard"'
+                script {
+                    sh 'echo test the app image'
+                    // Run the image in detach mode and map container port 5000 to localhost:5000
+                    sh '''#!/bin/bash
+                    docker run -d -p localhost:5000:5000 wizard-almanac:${APP_VERSION}
+                    '''      
+                    //Make a test reuest to the app and check result
+                    sh 'curl localhost:5000 | grep ${TEST_STRING}'
 
-                // Check the exit status (0 means success, non-zero means error)
-                def status = sh(script: 'echo $?', returnStdout: true).trim()
-                if (status == 0) {
-                    echo 'App is running as intened!'
-                } else {
-                    echo 'App error'
-                }                
+                    // Check the exit status (0 means success, non-zero means error)
+                    def status = sh(script: 'echo $?', returnStdout: true).trim()
+                    if (status == 0) {
+                        echo 'App is running as intened!'
+                    } else {
+                        echo 'App error'
+                    }           
+                }     
                 
             }
         }
